# Generated by Django 2.2.5 on 2021-04-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tender Title')),
                ('amount', models.IntegerField(verbose_name='Tender/Proposal security(Amount in BDT)')),
                ('publish_date', models.DateField(verbose_name='Tender Publish Date')),
                ('end_date', models.DateField(verbose_name='Tender Publish Date End')),
                ('pdf', models.FileField(upload_to='', verbose_name='Tender Details Pdf')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ministry_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.Ministry')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lisence_number', models.CharField(max_length=150, verbose_name='Lisence Number')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
