# Generated by Django 3.1.6 on 2021-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_employee', '0007_auto_20210603_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderupload',
            name='tender_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tender ID'),
        ),
    ]
