# Generated by Django 2.2.5 on 2021-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderupload',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Tender/Proposal security(Amount in BDT)'),
            preserve_default=False,
        ),
    ]
