# Generated by Django 2.2.5 on 2021-04-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('government_employee', '0003_applytenderholdershortlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holder.ApplyTender')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
