# Generated by Django 2.2.5 on 2021-04-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('government_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Your Phone Number')),
                ('trx_id', models.CharField(blank=True, max_length=35, null=True, verbose_name='Tender Free Trx ID')),
                ('bank_trx_id', models.IntegerField(verbose_name='Security Money Trx ID')),
                ('proposal_pdf', models.FileField(upload_to='', verbose_name='Proposal PDF')),
                ('working_exprience', models.IntegerField(verbose_name='Working Experience')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept')], default='Pending', max_length=7, verbose_name='Payment Status')),
                ('is_apply', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_employee.TenderUpload')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
