# Generated by Django 2.2.5 on 2021-04-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytender',
            name='working_exprience',
            field=models.TextField(verbose_name='Working Experience'),
        ),
    ]
