# Generated by Django 2.2.5 on 2021-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_auto_20210422_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytender',
            name='bank_trx_id',
            field=models.CharField(max_length=135, verbose_name='Security Money Trx ID'),
        ),
    ]
