# Generated by Django 3.1.6 on 2021-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0003_auto_20210501_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applytender',
            old_name='working_exprience',
            new_name='working_experience',
        ),
        migrations.AddField(
            model_name='applytender',
            name='bank_check_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Bank Check Image'),
        ),
        migrations.AddField(
            model_name='applytender',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket')], max_length=7, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='applytender',
            name='proposed_amount',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Proposed Amount'),
        ),
        migrations.AlterField(
            model_name='applytender',
            name='bank_trx_id',
            field=models.CharField(max_length=135, verbose_name='Security Money Bank_Check ID'),
        ),
        migrations.AlterField(
            model_name='applytender',
            name='trx_id',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Tender Fee Trx ID'),
        ),
    ]
