# Generated by Django 2.2.5 on 2021-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0004_auto_20210615_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytender',
            name='bank_trx_id',
            field=models.CharField(max_length=135, verbose_name='Security Money Bank Name & Check ID'),
        ),
        migrations.AlterField(
            model_name='applytender',
            name='trx_id',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Tender Fee Trans ID'),
        ),
    ]
